[CA-6] Added basic authentication login form + Bulma.
jonathangetachew/SoNet pull request #6
Opened 2019-12-01 23:15 UTC by yadirhb

2019-12-01 23:32 UTC, yadirhb commented
To complete this feature I had to add basic SecurityConfig, please check it all and approve the PR to merge.

2019-12-02 00:11 UTC, mahmoudreda400 approved these changes

2019-12-02 02:18 UTC, jonathangetachew requested changes
There are some conflicts in the pom file. Check it out.

2019-12-02 19:31 UTC, jonathangetachew approved these changes

2019-12-02 19:31 UTC, merged